### ISSUE TITLE
User account actions

### ISSUE THREAD

**Issue by mwild1** [snikket-im/snikket-web-portal#1]
This is a brain dump to start a discussion rather than concrete goals right now:

## Core actions

- Manage email address #2 
- Reset/change password #3  #4 
- Edit profile
  - Protocol: User Nickname #6 
  - Protocol: User Avatar #5 

## Additional
- Manage bookmarks #7 
- Manage devices #8 
- View security events #9 
- View/manage push registrations #10 
- Enable/disable OMEMO #11 
- Manage archive retention #12 
- Purge archive #13 
- Export data #14 
- Import data #15

**Comment by horazont** [comment]
Created individual issues for all of them, makes it easier to track.
