### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by Neustradamus** [snikket-im/snikket-web-portal#116]
Dear @mwild1,

Several days ago, I have sent you:

On https://snikket.org/ can you add the link on the logo in the footer.

Change "© 2021 Snikket Community Interest Company" by "© Copyright 2021-2022, Snikket Community Interest Company." or "© Copyright 2021-2022, Snikket Community Interest Company. All Rights Reserved."

**Comment by horazont** [comment]
This project is not about snikket.org. Do not spam the issue tracker about unrelated sites.
