### ISSUE TITLE
Add CI job to detect missing `make extract_translations`

### ISSUE THREAD

**Issue by horazont** [snikket-im/snikket-web-portal#118]
If `make extract_translations` is not run, new strings will not show up in Weblate or other tools.

We should run `make extract_translations` in the CI and see if the extracted file changes (except for the date, which changes even if nothing else changes), and let the CI fail if it does.

That way, we'll make sure that strings end up in the Weblate early.

The flow would roughly be:

- Install required dependencies
- Run `make extract_translations`
- Somehow roll back the change to the date in the .pot file
- Run `git diff` and check the exit code

**Comment by Rockycr** [comment]
So sreen shortb
