### ISSUE TITLE
Snikket-portal container is unhealthy

### ISSUE THREAD

**Issue by ScotchTartan** [snikket-im/snikket-web-portal#143]
I recently installed snikket for testing, i'm pretty new with containers so i'm not sure about this problem.
I can login into the webserver, and all seems to work fine without any issues.

My config:

```
SNIKKET_DOMAIN=snikket.local
SNIKKET_ADMIN_EMAIL=myemail@hello.local
SNIKKET_TWEAK_TURNSERVER_MIN_PORT=60000
SNIKKET_TWEAK_TURNSERVER_MAX_PORT=61023
SNIKKET_RETENTION_DAYS=7
SNIKKET_SITE_NAME=Snikket
```

I'm using UFW as recomended acording with Docs firewall.

Thanks in advance

**Comment by Zash** [comment]
Hi, thanks for the report. I'm wondering if this may be a duplicate of #126

**Comment by ScotchTartan** [comment]
Sorry, it's duplicate. I followed the instructions #126, and i resolved the problem.
Thanks
