### ISSUE TITLE
Allow choosing role when creating an invitation

### ISSUE THREAD

**Issue by mwild1** [snikket-im/snikket-web-portal#178]
By default all invitations create a "normal" user. Sometimes you want to invite someone as a "limited" user from the start. The interface should allow creating such invitations.

**Comment by Zash** [comment]
Needs a supporting change in [mod_http_admin_api](https://modules.prosody.im/mod_http_admin_api.html) in order to receive the alternate role.

**Comment by mwild1** [comment]
mod_http_admin_api commits [2aa66e928aa0](https://hg.prosody.im/prosody-modules/rev/2aa66e928aa0) (write) and [432efc39572f](https://hg.prosody.im/prosody-modules/rev/432efc39572f) (read).
