### ISSUE TITLE
UX: QR code button text

### ISSUE THREAD

**Issue by mwild1** [snikket-im/snikket-web-portal#38]
"Not on mobile?" has been reported to be ambiguous (and I tend to agree).

Most people I've tested with are not familiar with the name or usage of QR codes. Rather than "Show QR code" we need to speak to the user's intent when they may want to tap the button. Some options:

- "Send to device"
- "Scan code with device"
- "Show code for mobile device"

**Comment by horazont** [comment]
Moving to 0.1.2 because it needs translator interaction.
