### ISSUE TITLE
Add the ability to modify user roles

### ISSUE THREAD

**Issue by mwild1** [snikket-im/snikket-web-portal#42]
User objects in the API will gain a 'roles' array, but for Snikket purposes we can assume it will always consist of a single entry.

Planned possible roles:

  - prosody:admin
  - prosody:user
  - prosody:restricted

These values would map to text strings such as "Admin", "Normal" and "Limited".

It potentially makes sense to choose the role that someone will be when they accept an invitation (invitations with attached roles are already supported, but possibly just need a couple of lines to expose them in the admin API).

**Comment by horazont** [comment]
@mwild1 When you get a chance, it’d be good to get some input at what should be done on the prosody side to enforce the restricted role.

I imagine mod_firewall? Or a separate module?
