### ISSUE TITLE
add the possibility to manage snikket data and users data directly from the web portal

### ISSUE THREAD

**Issue by GodGoldfish** [snikket-im/snikket-web-portal#57]
HI,

i wanted to share my idea about the web-portal, i think it would be cool to be able to manage all the files related to a circle-group discussion or from the server in general, controling how much days the messages stay before they are deleted for a cicle discussion or applied in general, also have the view of the current usage of Snikket on the instance.

Thanks.

**Comment by mwild1** [comment]
Hi, thanks for the request! Recent releases have added support for monitoring the disk space consumed by file uploads, and placing a limit on them. It's unlikely we will implement more than this right now, for example it's not possible to link file uploads to a circle - the same file might be shared in multiple locations, for example.
