### ISSUE TITLE
"Create Admin Account" button broken

### ISSUE THREAD

**Issue by SamWhited** [snikket-im/snikket-web-portal#79]
After signing up and setting up your admin account and server if you then go back to my.snikket.org and hit the "Create admin account" button on the server you just created it goes to an error page that say "Sorry, it looks like this invitation link has expired!".

I would expect the button to not show up if you can't create another admin, or to have the ability to allow someone else to become an admin.

**Comment by mwild1** [comment]
Hey, that definitely seems like a bug (the button should disappear after use). I'll investigate. However as mentioned in the other issue, this is related to the Snikket hosted service only. Please report such issues to [hosting@snikket.org](mailto:hosting@snikket.org). Thanks!
