### ISSUE TITLE
No way to navigate back to server page from web portal

### ISSUE THREAD

**Issue by SamWhited** [snikket-im/snikket-web-portal#80]
After signing up you end up in the web portal. I foolishly couldn't figure out how to get back to `my.snikket.org` for a second, there was no indication what Snikket instance my organization/web portal was running on. Having a way to navigate back up to the main snikket server configuration page would be nice.

**Comment by mwild1** [comment]
Hey! Thanks for the issue report. This is relevant to the Snikket hosted service, however this repo is the per-instance web portal.

There currently isn't a public tracker for hosting-related issues, but I've made a note of this as a UX consideration, and see if I can find a way to address it.
