### ISSUE TITLE
Updating profile always fails with errors

### ISSUE THREAD

**Issue by mwild1** [snikket-im/snikket-web-portal#83]
In the latest release, attempting a user attempting to edit their profile (e.g. avatar, display name) via the web always fails with the errors:

- Not a valid choice
- The CSRF token is missing.

Reproduced in multiple deployments.

**Comment by horazont** [comment]
This is strange because I’m certain I tested at least setting an avatar in the smoketest.

**Comment by horazont** [comment]
But I can reproduce it now, it’s now broken. I’ll look into it ASAP.

**Comment by horazont** [comment]
Ok, it has something to do with Quart 0.15, scouting changelogs now.

**Comment by horazont** [comment]
Filed https://github.com/pgjones/quart/issues/126 upstream, reverting 486596f89f12916e61eca5f7a2de91576a910021 for now and strongly suggesting a bugfix release.

**Comment by horazont** [comment]
Hopefully fixed in b007afc90137fdf24b6b6740b83f78a3eab033de.

@mwild1 Can you test independently please? Also maybe another smoketest of the portal is due.

**Comment by horazont** [comment]
Released as 2021.05r1.
