### ISSUE TITLE
Parameterise the name of the stores to ease translation

### ISSUE THREAD

**Issue by linkmauve** [snikket-im/snikket-web-portal#88]
Instead of having three strings for “Get it on F-Droid”, “Get it on Google Play” “Get it on Apple Play”, it would be easier to translators to have a single “Get it on %(store_name)s”, same for the other strings mentioning a particular store.

**Comment by mwild1** [comment]
Thanks for the report.

I started work on this (it's obviously a trivial change in theory). However I ultimately decided not to implement this change for the following reasons:

As the strings are the 'alt' text of third-party buttons, the actual text is beyond our control. The app store button actually uses the text "Download on the App Store" so doesn't match the "Get it on" pattern.

It doesn't seem much benefit just combining the two remaining strings (and invalidating all the existing translations), so I'm going to leave it as-is for now. If we end up adding more platforms, that may change of course.
